feature(ui-ux): add nav menu
DeFiCh/defimetachain.org pull request #39
Opened 2022-09-03 10:34 UTC by kyleleow

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
- To add nav menu to desktop and mobile view
- To add temporary 3d model animation
- To add 3rd party library plugin to animate 3d model

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:
- Currently using box model to replace jellyfish because we haven't catch one yet
- Component in NavMenu couldn't be "cleanly" refactored due to the arbitrary value for `content` property of `::before` and `::after` pseudo element cannot accept react variables. And the reason to use pseudo elements are because we have to create the transition effect of gradient text or background effect

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*

2022-09-04 02:28 UTC, thedoublejay requested changes

2022-09-04 02:28 UTC, thedoublejay commented on src/components/home/Header.tsx
> +        <nav className="flex justify-between w-full items-center">
I think there's a position "top" for nav?

2022-09-04 02:28 UTC, thedoublejay commented on src/components/home/NavMenu.tsx
> +      <div className="py-3 px-5 flex items-center">
Better to have "a" element here. Better for accessibility. Also, when you hover youy can see the links. You can also use `_blank` as default if it's not an in page navigation.

2022-09-04 02:28 UTC, thedoublejay commented on src/components/home/NavMenu.tsx
> +          href=""
```suggestion
          href="https://github.com/DeFiCh/metachain"
```

2022-09-04 02:28 UTC, thedoublejay commented on src/components/home/NavMenu.tsx
> +          href=""
```suggestion
          href="https://github.com/DeFiCh/metachain/releases"
```

2022-09-04 02:28 UTC, thedoublejay commented on src/components/home/NavMenu.tsx
> +          href=""
```suggestion
          href="https://defichain.com"
```

2022-09-04 02:28 UTC, thedoublejay commented on src/components/home/NavMenu.tsx
> +          href=""
```suggestion
          href="https://defichain.com/white-paper"
```

2022-09-04 09:08 UTC, kyleleow commented on src/components/home/NavMenu.tsx
> +          href=""
i think we have a separate white paper for DMC

2022-09-04 09:09 UTC, kyleleow commented on src/components/home/Header.tsx
> +        <nav className="flex justify-between w-full items-center">
do you mean the nav will be fixed on top upon scrolling down? Confirmed with designer last time that they won't be fixed

2022-09-05 02:06 UTC, thedoublejay approved these changes

2022-09-05 02:06 UTC, merged